name: Bug report
description: Report a reproducible problem in CleanMacOS
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this. Please provide enough detail to reproduce the issue.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: Describe the bug clearly.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact steps and selected categories/settings.
      placeholder: |
        1. Open app
        2. Select category ...
        3. Click ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Terminal output or errors
      description: Paste relevant output from the app terminal panel.
      render: shell
  - type: input
    id: version
    attributes:
      label: App version
      placeholder: v0.1.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: macOS version
      options:
        - macOS 15
        - macOS 14
        - Other
    validations:
      required: true
