name: Feature request
description: Suggest a new capability or UX improvement
title: "[Feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Suggest a feature with user value, technical scope, and acceptance criteria.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe expected behavior and UX.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: Scope / impact
      options:
        - Small
        - Medium
        - Large
    validations:
      required: true
